# Generated by Django 5.0.7 on 2024-08-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestslog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='requestslog',
            name='country',
        ),
    ]
