# Generated by Django 5.0.7 on 2024-08-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_requestslog_city_remove_requestslog_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestslog',
            old_name='referer',
            new_name='referred_to',
        ),
        migrations.RemoveField(
            model_name='requestslog',
            name='host',
        ),
    ]
